"""Added relationship to the tables.

Revision ID: 72fa0ea05859
Revises: bcd0ac838ce7
Create Date: 2019-04-23 19:42:58.081658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fa0ea05859'
down_revision = 'bcd0ac838ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'author')
    # ### end Alembic commands ###
