"""Changews to the pitches and users table.

Revision ID: 9c896bc9eb47
Revises: 72fa0ea05859
Create Date: 2019-04-24 09:13:20.714455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c896bc9eb47'
down_revision = '72fa0ea05859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'category_id')
    op.drop_column('pitches', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('category_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
